{% set version = "1.10.0" %}
{% set test_version = ".".join(version.split('.')[:2] + ['0']) %}
{% set ze_version = "1.3" %}

package:
  name: intel-level-zero
  version: {{ version }}

source:
  - url: https://github.com/oneapi-src/level-zero/archive/refs/tags/v{{ version }}.tar.gz
    sha256: 2811e4128ff6114020d0a147c2769b9b2e782e68ad49827685c33b9e716bf6ab
    folder: level-zero

build:
  number: 0
  skip: true  # [not (x86 and (linux))]

requirements:
  build:
    - {{ compiler('cxx') }}
    - cmake
    - make

outputs:
  - name: level-zero
    version: {{ version }}
    script: move-level-zero.sh
    requirements:
      build:
        - {{ compiler('cxx') }}
    about:
      home: https://github.com/oneapi-src/level-zero
      license: MIT
      license_family: MIT
      description: |
        oneAPI Level Zero
    test:
      commands:
        - ls -A1 ${PREFIX}/lib   # [linux]
        - test -f ${PREFIX}/lib/libze_loader.so.1   # [linux]
        - test -f ${PREFIX}/lib/libze_loader.so.{{ test_version }}   # [linux]
        - test -f ${PREFIX}/lib/libze_tracing_layer.so.1   # [linux]
        - test -f ${PREFIX}/lib/libze_tracing_layer.so.{{ test_version }}   # [linux]
        - test -f ${PREFIX}/lib/libze_validation_layer.so.1   # [linux]
        - test -f ${PREFIX}/lib/libze_validation_layer.so.{{ test_version }}   # [linux]
  - name: level-zero-devel
    version: {{ version }}
    script: move-level-zero-devel.sh
    requirements:
      build:
        - {{ compiler('cxx') }}
      run:
        - {{ pin_subpackage('level-zero', exact=True) }}
    about:
      home: https://github.com/oneapi-src/level-zero
      license: MIT
      license_family: MIT
      description: |
        oneAPI Level Zero development libs
    test:
      commands:
        - test -f ${PREFIX}/lib/libze_loader.so   # [linux]
        - test -f ${PREFIX}/lib/libze_tracing_layer.so   # [linux]
        - test -f ${PREFIX}/lib/libze_validation_layer.so   # [linux]
        - test -d ${PREFIX}/include/level_zero   # [linux]
        - test -d ${PREFIX}/include/level_zero/loader   # [linux]
        - test -d ${PREFIX}/include/level_zero/layers   # [linux]
        - test -f ${PREFIX}/lib/pkgconfig/libze_loader.pc   # [linux]
        - test -f ${PREFIX}/lib/pkgconfig/level-zero.pc   # [linux]

about:
  home: https://github.com/oneapi-src/level-zero
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Intel(R) level zero libraries

extra:
  feedstock-name: level-zero
  recipe-maintainers:
    - oleksandr-pavlyk
    - kurapov-peter
