{% set version = "1.20.3" %}
{% set so_version1 = ".".join(version.split('.')[:1]) %}
{% set ze_version = "1.3" %}

package:
  name: intel-level-zero
  version: {{ version }}

source:
  - url: https://github.com/oneapi-src/level-zero/archive/refs/tags/v{{ version }}.tar.gz
    sha256: 6b883faca0c0b3abc333a08c9ef4ddc1ec1b93acdb06625f8b526f6650a3bd85
    folder: level-zero

build:
  number: 0
  skip: true  # [not (x86 and (linux or win))]

requirements:
  build:
    - {{ compiler('cxx') }}
    - {{ stdlib("c") }}
    - cmake
    - ninja
    - mako

outputs:
  - name: level-zero
    version: {{ version }}
    script: move-level-zero.sh  # [linux]
    script: move-level-zero.bat  # [win]
    requirements:
      build:
        - {{ compiler('cxx') }}
        - {{ stdlib("c") }}
    about:
      home: https://github.com/oneapi-src/level-zero
      license: MIT
      license_family: MIT
      description: |
        oneAPI Level Zero
    test:
      commands:
        - ls -A1 ${PREFIX}/lib  # [linux]
        - dir /S "%LIBRARY_BIN%"  # [win]
        - if not exist %LIBRARY_BIN%\\ze_loader.dll exit 1  # [win]
        - if not exist %LIBRARY_BIN%\\ze_tracing_layer.dll exit 1  # [win]
        - if not exist %LIBRARY_BIN%\\ze_validation_layer.dll exit 1  # [win]
        - test -f ${PREFIX}/lib/libze_loader.so.{{ so_version1 }}  # [linux]
        - test -f ${PREFIX}/lib/libze_loader.so.{{ version }}  # [linux]
        - test -f ${PREFIX}/lib/libze_tracing_layer.so.{{ so_version1 }}  # [linux]
        - test -f ${PREFIX}/lib/libze_tracing_layer.so.{{ version }}  # [linux]
        - test -f ${PREFIX}/lib/libze_validation_layer.so.{{ so_version1 }}  # [linux]
        - test -f ${PREFIX}/lib/libze_validation_layer.so.{{ version }}  # [linux]
  - name: level-zero-devel
    version: {{ version }}
    script: move-level-zero-devel.sh  # [linux]
    script: move-level-zero-devel.bat  # [win]
    build:
      run_exports:
        - {{ pin_subpackage('level-zero', max_pin="x") }}
    requirements:
      build:
        - {{ compiler('cxx') }}
        - {{ stdlib("c") }}
      run:
        - {{ pin_subpackage('level-zero', exact=True) }}
    about:
      home: https://github.com/oneapi-src/level-zero
      license: MIT
      license_family: MIT
      description: |
        oneAPI Level Zero development libs
    test:
      commands:
        - dir "%LIBRARY_LIB%"  # [win]
        - if not exist %LIBRARY_LIB%\\ze_loader.lib exit 1  # [win]
        - if not exist %LIBRARY_LIB%\\ze_tracing_layer.lib exit 1  # [win]
        - if not exist %LIBRARY_LIB%\\ze_validation_layer.lib exit 1  # [win]
        - dir /S "%LIBRARY_INC%"  # [win]
        - test -f ${PREFIX}/lib/libze_loader.so  # [linux]
        - test -f ${PREFIX}/lib/libze_tracing_layer.so  # [linux]
        - test -f ${PREFIX}/lib/libze_validation_layer.so  # [linux]
        - test -d ${PREFIX}/include/level_zero  # [linux]
        - test -d ${PREFIX}/include/level_zero/loader  # [linux]
        - test -d ${PREFIX}/include/level_zero/layers  # [linux]
        - test -f ${PREFIX}/lib/pkgconfig/libze_loader.pc  # [linux]
        - test -f ${PREFIX}/lib/pkgconfig/level-zero.pc  # [linux]

about:
  home: https://github.com/oneapi-src/level-zero
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Intel(R) level zero libraries

extra:
  feedstock-name: level-zero
  recipe-maintainers:
    - oleksandr-pavlyk
    - kurapov-peter
    - ZzEeKkAa
    - ilya-lavrenov
